version: '3.8'
services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: ["mongo:/data/db"]

  backend:
    build: ./backend
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/smash
      - ORIGIN=http://localhost:5173
      - ADMIN_USERS=admin:changeme
    ports: ["5000:5000"]
    depends_on: [mongo]

  frontend:
    build: ./frontend
    ports: ["5173:80"]
    depends_on: [backend]

volumes:
  mongo: {}

